# Generated by Django 4.0.3 on 2022-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_date_alter_post_author_alter_post_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Excerpt',
            new_name='excerpt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Date',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
